### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by nipnipj** [ConnorDonegan/geostan#14]
```
make: *** [/usr/lib/R/etc/Makeconf:176: stanExports_foundation.o] Error 1
ERROR: compilation failed for package ‘geostan’
* removing ‘/home/cuysaurus/R/x86_64-pc-linux-gnu-library/4.2/geostan’
Warning in install.packages :
  installation of package ‘geostan’ had non-zero exit status
```

**Comment by nipnipj** [comment]
I've tried both `install.packages('geostan')` and `remotes::install_github('ConnorDonegan/geostan')` failed.
I just tried again, after reinstalling `stanheaders` and `rstan`. `geostan` has been installed correctly.

**Comment by ConnorDonegan** [comment]
Okay great, glad to hear it. Let me know if you come across any issues using the software or have questions.
