### ISSUE TITLE
JOSS Review: Performance claims

### ISSUE THREAD

**Issue by wcjochem** [ConnorDonegan/geostan#3]
The manuscript states that the CAR model is efficient for fitting models to county-level data for the entire U.S. on a laptop (lines 83-86). Do you have a worked example for users that demonstrates that claim? Alternatively, please provide a reference in the manuscript to a paper where the model is used at that scale to provide evidence.

https://github.com/openjournals/joss-reviews/issues/4716

**Comment by ConnorDonegan** [comment]
Thanks @wcjochem, I'm adding a reference to the OSF pre-print "Building spatial conditional auto-regressive models in the Stan programming language" (https://osf.io/3ey65/) which has a demonstration analysis with US county data and also a study of sampling efficiency with head-to-head comparison between my Stan functions and NIMBLE's `dcar proper`.

**Comment by wcjochem** [comment]
Many thanks. Closing this as it has now been addressed in the review.
