### ISSUE TITLE
JOSS Review: Documentation of `geostan_fit` methods

### ISSUE THREAD

**Issue by wcjochem** [ConnorDonegan/geostan#5]
Overall I found the functions to be adequately documented throughout; however, I think it could be improved if you could split the documentation for "`geostan_fit` methods" into separate pages for plotting/printing, extracting, predicting. Currently these are contained in a single documentation page and are indexed under one topic. These functions cover a wide range steps and it would be easier to find that documentation and I think it would make it more readable for users to have separate pages.

https://github.com/openjournals/joss-reviews/issues/4716

**Comment by ConnorDonegan** [comment]
Thanks, this is a really helpful suggestion. I see its looking cluttered right now.

I'm breaking the `geostan_fit` methods documentation into the following pages:

 - Extract residuals, fitted values, or spatial trend
 - predict 
 - print or plot model results
 - extract MCMC samples (as.matrix, as.data.frame, as.array)

I'd like to push this and the other changes to CRAN just after the publication is finished and can be cited.

**Comment by wcjochem** [comment]
Thanks, I'll close this issue now since it has been addressed. Feel free to re-open if you want to keep it for reference until you push the changes.
